-- 아동복지시설. 설계 설명은 docs/wiki/data-model.md 참고
CREATE TABLE facility (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             VARCHAR(100)     NOT NULL,
    facility_type    VARCHAR(30)      NOT NULL,
    type_confirmed   BOOLEAN          NOT NULL DEFAULT FALSE,
    address_raw      VARCHAR(300)     NOT NULL,
    address          VARCHAR(300)     NOT NULL,
    sido             VARCHAR(20),
    sigungu          VARCHAR(30),
    latitude         DOUBLE PRECISION,
    longitude        DOUBLE PRECISION,
    source           VARCHAR(30)      NOT NULL,
    source_ref       VARCHAR(50),
    source_base_date DATE,
    created_at       TIMESTAMPTZ      NOT NULL,
    updated_at       TIMESTAMPTZ      NOT NULL,
    CONSTRAINT uk_facility_source UNIQUE (source, source_ref),
    CONSTRAINT ck_facility_type CHECK (facility_type IN (
        'CHILD_CARE', 'GROUP_HOME', 'TEMPORARY_PROTECTION',
        'PROTECTIVE_TREATMENT', 'SELF_RELIANCE', 'OTHER', 'UNKNOWN'))
);
